# Base configs
baseurl: /astral

# UI configs
title: "Shivani Patel"
name: "Shivani Patel"
bio: "computer engineer"
social_urls:
  facebook: "https://www.facebook.com/shivanipatel"
  instagram: "https://www.instagram.com/shivipatel7"
